### ISSUE TITLE
return frontmatter attributes in a named key

### ISSUE THREAD

**Issue by tbeseda** [architect/arcdown#5]
Instead of [globbing the frontmatter onto the returned object](https://github.com/architect/arcdown/blob/main/src/index.js#L87), we should probably nest the frontmatter attributes

What should the key be named? I vote `frontmatter` to be explicit, but `attributes` is another option.
Does `title` remain a top level attribute? or do `title` and `slug` get moved into `frontmatter` object?

**Comment by macdonst** [comment]
Yeah, it would be nice if the render returned something like:

```javascript
const {
  html,     // the good stuff: HTML!
  tocHtml,  // an HTML table of contents
  slug,     // a URL-friendly slug
  frontmatter,    // all the attributes from frontmatter
  // ...       any other attributes ¯\_(ツ)_/¯
} = await render(file, options)
```

I think `title` should be in the `frontmatter` since that is where it is defined.

As for `slug` where do we use it? I've checked a couple of our sites and it doesn't seem to use a `slug` generated from the title.
